#' Extract data-frame with forecasts for validation violin plot
#'
#' @param time_period_result output from  \code{forecast_time_period_epiestim}
#'
#' @return Data frame with forecasts at all time-points
#' @export
#'
#' @examples
#' plover_data <- data.frame(
#'           epiWeek_date = as.Date(c('2022-10-02', '2022-10-09',
#'                      '2022-10-16', '2022-10-23', '2022-10-30',
#'                      '2022-11-06', '2022-11-13', '2022-11-20',
#'                       '2022-11-27', '2022-12-04')),
#'           epiWeek_year = c(2022,2022,2022,2022,
#'                       2022,2022,2022,2022,2022,2022),
#'            Epiweek = c(40,41,42,43,44,45,46,47,48,49),
#'            flu_a = c(17,19,32,38,43,45,73,88,94,105),
#'            flu_b = c(24,31,39,45,50,52,68,83,89,97))
#'
#' weekly_plover_data <- get_weekly_plover(plover_data)
#'
#' plover_dat_clean <- get_weekly_plover_by_date_type(
#'                              weekly_plover_data,
#'                              'flu_a',
#'                              '2022-10-01',
#'                              '2022-12-05')
#'
#' time_period_result <- forecast_time_period_epiestim(data = plover_dat_clean,
#' start_date_str = "2022-10-02", n_days = 14, type = "flu_a")
#'
#' create_forecast_df(time_period_result)
#'
#'
create_forecast_df <- function(time_period_result) {
  results <- lapply(time_period_result, function(i) {
    pred_samples_with_quantile_helper(tp = i, aggregate_unit =  time_period_result[[1]][["quantile_unit"]])
  })
  results <- do.call(rbind.data.frame, results)
  return(results)
}


#' Helper function to extract dataframe with week ahead forecasts for Violin plot
#'
#' @param tp element from list output generated by \code{forecast_time_period_epiestim}
#' @param aggregate_unit  Time forecasted samples are aggregated by (weekly or daily)
#'
#'
#' @return Dataframe of forecasts at a single time-point (single element from list input)

pred_samples_with_quantile_helper <- function(tp, aggregate_unit = NULL) {
  value <- quantile_date <- daily_value <- NULL
  cur_samples_with_quantile <- extract_quantile_epiestim(tp)
  seq_time_length <- seq_len(nrow(cur_samples_with_quantile))
  if(aggregate_unit == "weekly") {
    cur_samples_with_quantile$pred_horizon <- paste(seq_time_length, "week ahead")
    cur_samples_with_week_date <- extract_sim_samples_epiestim(tp, aggregate_unit = eval(parse(text="aggregate_unit")))
    cur_samples_with_quantile <-  cur_samples_with_quantile %>%
      dplyr::left_join(cur_samples_with_week_date, by = "quantile_date") %>%
      dplyr::rename(sim_draws = value, weekly_date = quantile_date)
  } else if (aggregate_unit == "daily") {
    cur_samples_with_quantile$pred_horizon <- paste(seq_time_length, "days ahead")
    cur_samples_with_daily_date <- extract_sim_samples_epiestim(tp, aggregate_unit = eval(parse(text="aggregate_unit")))
    cur_samples_with_quantile <-  cur_samples_with_quantile %>%
      dplyr::left_join(cur_samples_with_daily_date, by = "quantile_date") %>%
      dplyr::rename(sim_draws = daily_value, daily_date = quantile_date)
  }



  return(cur_samples_with_quantile)

}

